<style>
:root {
	--body-bg: #f0f2f5;
	--header-background: #ffffff;
	--header-color: #000000;
	--header-hover-color: #333333;
	--header-search-color: #f0f2f5;
	--main: #c01b1c;
	--main-hover: #00b324;
	--main-color: #ffffff;
	--main-hover-color: #ffffff;
	--chat-outgoing: #fff9f9;
	--plyr-color-main: #00b324;
	--plyr-control-toggle-checked-background: transparent;
	--plyr-video-control-background-hover: rgba(255, 255, 255, 0.2);
	--plyr-range-fill-background: #fff;
	--plyr-range-track-height: 3px;
}

<?php
	if (!empty($wo['reactions_types'])) {
    foreach ($wo['reactions_types'] as $key => $value) {
?>
.reaction-<?php echo $value['id'];?>::after {content: "<?php echo $value['name'];?>";}
<?php } } ?>
</style>