<div class="pages-block user-data" data-page-id="2">
  <div class="pages">
    <div class="pagesImg">
      <a href="https://vseti.by/Strawberry" data-ajax="?link1=timeline&amp;u=Strawberry"><img
          src="https://vseti.space/upload/photos/2022/07/cmYHytmdHURhffP4Qjsx_22_eae0151b3d9225e47dc079750b89294a_avatar.jpg"
          alt="Клубничка❤️"></a>
    </div>
    <div class="pagesText">
      <span><a href="https://vseti.by/Strawberry" data-ajax="?link1=timeline&amp;u=Strawberry">Клубничка❤️&nbsp;<span
            class="verified-color fs-14" title="" data-toggle="tooltip"
            data-original-title="Верифицированная страница">&nbsp;<img
              src="https://vseti.by/themes/wondertag/img/icons/verification.svg"></span></a></span>
      <p> 24 Подписчика</p>
    </div>
  </div>
</div>